// Colors
export const themeColor = '#3A3748'
export const darkerThemeColor = '#343142'
export const blue = '#CDC6E8'
export const gray = '#EAEBEC'
export const green = '#2AC3B8'
export const darkGray = '#B1B3B4'
export const lightGray = '#F5F7FB'
export const riverBlue = '#3498db'
export const violet = '#8F80FB'
export const belizeBlue = '#2980b9'
// export const lightGray = '#EBEDF1'
